SELECT *
FROM (
SELECT MIN(DT_INI_TRV) DT_INI_VIAGEM,
MAX(DT_FIM_TRV) DT_FIM_VIAGEM
FROM AD_ADVTRC
WHERE IDINSTPRN = :IDINSTPRN AND
IDINSTTAR = :IDINSTTAR
) TEMP_NAC,
(
SELECT MIN(DATINI) DT_INI_VIAGEM_INT,
MAX(DATFIM) DT_FIM_VIAGEM_INT
FROM AD_ADVTRCINT
WHERE IDINSTPRN = :IDINSTPRN AND
IDINSTTAR = :IDINSTTAR
) TEMP_INT