SELECT *
FROM AD_ADVRATVLR
WHERE :FRACAO >= SUBSTR(DIFHORAS,1, 5)+0 AND :FRACAO < SUBSTR(DIFHORAS,7, 5)+0 AND
COMPRHOSP = :COMPRHOSP AND CIDLIMITR = :CIDLIMITR AND CUSTERC = :CUSTERC AND DIFDIAS = :DIFDIAS